package org.overworld.tarotbooth.sound;

import java.util.HashMap;

import org.overworld.tarotbooth.model.Deck.Card;
import org.overworld.tarotbooth.model.Position;
import org.springframework.stereotype.Component;

import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;

@Component
public class SoundLibrary extends HashMap<String, Media> {

	private static final long serialVersionUID = 5555776105538766715L;

	private MediaPlayer fallback = new MediaPlayer(new Media(SoundLibrary.class.getResource("I09.mp3").toString()));
	
	{
		this.put("L01", new Media(SoundLibrary.class.getResource("L01.mp3").toString()));
		this.put("L02", new Media(SoundLibrary.class.getResource("L02.mp3").toString()));
		this.put("L03", new Media(SoundLibrary.class.getResource("L03.mp3").toString()));
		this.put("L04", new Media(SoundLibrary.class.getResource("L04.mp3").toString()));
		this.put("L05", new Media(SoundLibrary.class.getResource("L05.mp3").toString()));
		this.put("L06", new Media(SoundLibrary.class.getResource("L06.mp3").toString()));
		this.put("A01", new Media(SoundLibrary.class.getResource("A01.mp3").toString()));
		this.put("A02", new Media(SoundLibrary.class.getResource("A02.mp3").toString()));
		this.put("A03", new Media(SoundLibrary.class.getResource("A03.mp3").toString()));
		this.put("A04", new Media(SoundLibrary.class.getResource("A04.mp3").toString()));
		this.put("A05", new Media(SoundLibrary.class.getResource("A05.mp3").toString()));
		this.put("A06", new Media(SoundLibrary.class.getResource("A06.mp3").toString()));
		this.put("C01", new Media(SoundLibrary.class.getResource("C01.mp3").toString()));
		this.put("C01F", new Media(SoundLibrary.class.getResource("C01F.mp3").toString()));
		this.put("C01P", new Media(SoundLibrary.class.getResource("C01P.mp3").toString()));
		this.put("C01R", new Media(SoundLibrary.class.getResource("C01R.mp3").toString()));
		this.put("C02", new Media(SoundLibrary.class.getResource("C02.mp3").toString()));
		this.put("C02F", new Media(SoundLibrary.class.getResource("C02F.mp3").toString()));
		this.put("C02P", new Media(SoundLibrary.class.getResource("C02P.mp3").toString()));
		this.put("C02R", new Media(SoundLibrary.class.getResource("C02R.mp3").toString()));
		this.put("C03", new Media(SoundLibrary.class.getResource("C03.mp3").toString()));
		this.put("C03F", new Media(SoundLibrary.class.getResource("C03F.mp3").toString()));
		this.put("C03P", new Media(SoundLibrary.class.getResource("C03P.mp3").toString()));
		this.put("C03R", new Media(SoundLibrary.class.getResource("C03R.mp3").toString()));
		this.put("C04", new Media(SoundLibrary.class.getResource("C04.mp3").toString()));
		this.put("C04F", new Media(SoundLibrary.class.getResource("C04F.mp3").toString()));
		this.put("C04P", new Media(SoundLibrary.class.getResource("C04P.mp3").toString()));
		this.put("C04R", new Media(SoundLibrary.class.getResource("C04R.mp3").toString()));
		this.put("C05", new Media(SoundLibrary.class.getResource("C05.mp3").toString()));
		this.put("C05F", new Media(SoundLibrary.class.getResource("C05F.mp3").toString()));
		this.put("C05P", new Media(SoundLibrary.class.getResource("C05P.mp3").toString()));
		this.put("C05R", new Media(SoundLibrary.class.getResource("C05R.mp3").toString()));
		this.put("C06", new Media(SoundLibrary.class.getResource("C06.mp3").toString()));
		this.put("C06F", new Media(SoundLibrary.class.getResource("C06F.mp3").toString()));
		this.put("C06P", new Media(SoundLibrary.class.getResource("C06P.mp3").toString()));
		this.put("C06R", new Media(SoundLibrary.class.getResource("C06R.mp3").toString()));
		this.put("C07", new Media(SoundLibrary.class.getResource("C07.mp3").toString()));
		this.put("C07F", new Media(SoundLibrary.class.getResource("C07F.mp3").toString()));
		this.put("C07P", new Media(SoundLibrary.class.getResource("C07P.mp3").toString()));
		this.put("C07R", new Media(SoundLibrary.class.getResource("C07R.mp3").toString()));
		this.put("C08", new Media(SoundLibrary.class.getResource("C08.mp3").toString()));
		this.put("C08F", new Media(SoundLibrary.class.getResource("C08F.mp3").toString()));
		this.put("C08R", new Media(SoundLibrary.class.getResource("C08R.mp3").toString()));
		this.put("C09", new Media(SoundLibrary.class.getResource("C09.mp3").toString()));
		this.put("C09F", new Media(SoundLibrary.class.getResource("C09F.mp3").toString()));
		this.put("C09P", new Media(SoundLibrary.class.getResource("C09P.mp3").toString()));
		this.put("C09R", new Media(SoundLibrary.class.getResource("C09R.mp3").toString()));
		this.put("C10", new Media(SoundLibrary.class.getResource("C10.mp3").toString()));
		this.put("C10F", new Media(SoundLibrary.class.getResource("C10F.mp3").toString()));
		this.put("C10P", new Media(SoundLibrary.class.getResource("C10P.mp3").toString()));
		this.put("C10R", new Media(SoundLibrary.class.getResource("C10R.mp3").toString()));
		this.put("C11", new Media(SoundLibrary.class.getResource("C11.mp3").toString()));
		this.put("C11F", new Media(SoundLibrary.class.getResource("C11F.mp3").toString()));
		this.put("C11P", new Media(SoundLibrary.class.getResource("C11P.mp3").toString()));
		this.put("C11R", new Media(SoundLibrary.class.getResource("C11R.mp3").toString()));
		this.put("C12", new Media(SoundLibrary.class.getResource("C12.mp3").toString()));
		this.put("C12F", new Media(SoundLibrary.class.getResource("C12F.mp3").toString()));
		this.put("C12P", new Media(SoundLibrary.class.getResource("C12P.mp3").toString()));
		this.put("C12R", new Media(SoundLibrary.class.getResource("C12R.mp3").toString()));
		this.put("C13", new Media(SoundLibrary.class.getResource("C13.mp3").toString()));
		this.put("C13F", new Media(SoundLibrary.class.getResource("C13F.mp3").toString()));
		this.put("C13P", new Media(SoundLibrary.class.getResource("C13P.mp3").toString()));
		this.put("C13R", new Media(SoundLibrary.class.getResource("C13R.mp3").toString()));
		this.put("C14", new Media(SoundLibrary.class.getResource("C14.mp3").toString()));
		this.put("C14F", new Media(SoundLibrary.class.getResource("C14F.mp3").toString()));
		this.put("C14P", new Media(SoundLibrary.class.getResource("C14P.mp3").toString()));
		this.put("C14R", new Media(SoundLibrary.class.getResource("C14R.mp3").toString()));
		this.put("CO8P", new Media(SoundLibrary.class.getResource("CO8P.mp3").toString()));
		this.put("E01", new Media(SoundLibrary.class.getResource("E01.mp3").toString()));
		this.put("E02", new Media(SoundLibrary.class.getResource("E02.mp3").toString()));
		this.put("E03", new Media(SoundLibrary.class.getResource("E03.mp3").toString()));
		this.put("X01", new Media(SoundLibrary.class.getResource("X01.mp3").toString()));
		this.put("X02", new Media(SoundLibrary.class.getResource("X02.mp3").toString()));
		this.put("X03", new Media(SoundLibrary.class.getResource("X03.mp3").toString()));
		this.put("I01", new Media(SoundLibrary.class.getResource("I01.mp3").toString()));
		this.put("I02", new Media(SoundLibrary.class.getResource("I02.mp3").toString()));
		this.put("I03", new Media(SoundLibrary.class.getResource("I03.mp3").toString()));
		this.put("I04", new Media(SoundLibrary.class.getResource("I04.mp3").toString()));
		this.put("I05", new Media(SoundLibrary.class.getResource("I05.mp3").toString()));
		this.put("I06", new Media(SoundLibrary.class.getResource("I06.mp3").toString()));
		this.put("I07", new Media(SoundLibrary.class.getResource("I07.mp3").toString()));
		this.put("I08", new Media(SoundLibrary.class.getResource("I08.mp3").toString()));
		this.put("I09", new Media(SoundLibrary.class.getResource("I09.mp3").toString()));
		this.put("M00", new Media(SoundLibrary.class.getResource("M00.mp3").toString()));
		this.put("M00F", new Media(SoundLibrary.class.getResource("M00F.mp3").toString()));
		this.put("M00P", new Media(SoundLibrary.class.getResource("M00P.mp3").toString()));
		this.put("M00R", new Media(SoundLibrary.class.getResource("M00R.mp3").toString()));
		this.put("M01", new Media(SoundLibrary.class.getResource("M01.mp3").toString()));
		this.put("M01F", new Media(SoundLibrary.class.getResource("M01F.mp3").toString()));
		this.put("M01P", new Media(SoundLibrary.class.getResource("M01P.mp3").toString()));
		this.put("M02", new Media(SoundLibrary.class.getResource("M02.mp3").toString()));
		this.put("M02F", new Media(SoundLibrary.class.getResource("M02F.mp3").toString()));
		this.put("M02P", new Media(SoundLibrary.class.getResource("M02P.mp3").toString()));
		this.put("M02R", new Media(SoundLibrary.class.getResource("M02R.mp3").toString()));
		this.put("M03", new Media(SoundLibrary.class.getResource("M03.mp3").toString()));
		this.put("M03F", new Media(SoundLibrary.class.getResource("M03F.mp3").toString()));
		this.put("M03P", new Media(SoundLibrary.class.getResource("M03P.mp3").toString()));
		this.put("M03R", new Media(SoundLibrary.class.getResource("M03R.mp3").toString()));
		this.put("M04", new Media(SoundLibrary.class.getResource("M04.mp3").toString()));
		this.put("M04F", new Media(SoundLibrary.class.getResource("M04F.mp3").toString()));
		this.put("M04P", new Media(SoundLibrary.class.getResource("M04P.mp3").toString()));
		this.put("M04R", new Media(SoundLibrary.class.getResource("M04R.mp3").toString()));
		this.put("M05", new Media(SoundLibrary.class.getResource("M05.mp3").toString()));
		this.put("M05F", new Media(SoundLibrary.class.getResource("M05F.mp3").toString()));
		this.put("M05P", new Media(SoundLibrary.class.getResource("M05P.mp3").toString()));
		this.put("M05R", new Media(SoundLibrary.class.getResource("M05R.mp3").toString()));
		this.put("M06", new Media(SoundLibrary.class.getResource("M06.mp3").toString()));
		this.put("M06F", new Media(SoundLibrary.class.getResource("M06F.mp3").toString()));
		this.put("M06P", new Media(SoundLibrary.class.getResource("M06P.mp3").toString()));
		this.put("M06R", new Media(SoundLibrary.class.getResource("M06R.mp3").toString()));
		this.put("M07", new Media(SoundLibrary.class.getResource("M07.mp3").toString()));
		this.put("M07F", new Media(SoundLibrary.class.getResource("M07F.mp3").toString()));
		this.put("M07P", new Media(SoundLibrary.class.getResource("M07P.mp3").toString()));
		this.put("M07R", new Media(SoundLibrary.class.getResource("M07R.mp3").toString()));
		this.put("M08", new Media(SoundLibrary.class.getResource("M08.mp3").toString()));
		this.put("M08F", new Media(SoundLibrary.class.getResource("M08F.mp3").toString()));
		this.put("M08P", new Media(SoundLibrary.class.getResource("M08P.mp3").toString()));
		this.put("M08R", new Media(SoundLibrary.class.getResource("M08R.mp3").toString()));
		this.put("M09", new Media(SoundLibrary.class.getResource("M09.mp3").toString()));
		this.put("M09F", new Media(SoundLibrary.class.getResource("M09F.mp3").toString()));
		this.put("M09P", new Media(SoundLibrary.class.getResource("M09P.mp3").toString()));
		this.put("M09R", new Media(SoundLibrary.class.getResource("M09R.mp3").toString()));
		this.put("M10", new Media(SoundLibrary.class.getResource("M10.mp3").toString()));
		this.put("M10F", new Media(SoundLibrary.class.getResource("M10F.mp3").toString()));
		this.put("M10P", new Media(SoundLibrary.class.getResource("M10P.mp3").toString()));
		this.put("M10R", new Media(SoundLibrary.class.getResource("M10R.mp3").toString()));
		this.put("M11", new Media(SoundLibrary.class.getResource("M11.mp3").toString()));
		this.put("M11F", new Media(SoundLibrary.class.getResource("M11F.mp3").toString()));
		this.put("M11P", new Media(SoundLibrary.class.getResource("M11P.mp3").toString()));
		this.put("M11R", new Media(SoundLibrary.class.getResource("M11R.mp3").toString()));
		this.put("M12", new Media(SoundLibrary.class.getResource("M12.mp3").toString()));
		this.put("M12F", new Media(SoundLibrary.class.getResource("M12F.mp3").toString()));
		this.put("M12P", new Media(SoundLibrary.class.getResource("M12P.mp3").toString()));
		this.put("M12R", new Media(SoundLibrary.class.getResource("M12R.mp3").toString()));
		this.put("M13", new Media(SoundLibrary.class.getResource("M13.mp3").toString()));
		this.put("M13F", new Media(SoundLibrary.class.getResource("M13F.mp3").toString()));
		this.put("M13P", new Media(SoundLibrary.class.getResource("M13P.mp3").toString()));
		this.put("M13R", new Media(SoundLibrary.class.getResource("M13R.mp3").toString()));
		this.put("M14", new Media(SoundLibrary.class.getResource("M14.mp3").toString()));
		this.put("M14F", new Media(SoundLibrary.class.getResource("M14F.mp3").toString()));
		this.put("M14P", new Media(SoundLibrary.class.getResource("M14P.mp3").toString()));
		this.put("M14R", new Media(SoundLibrary.class.getResource("M14R.mp3").toString()));
		this.put("M15", new Media(SoundLibrary.class.getResource("M15.mp3").toString()));
		this.put("M15F", new Media(SoundLibrary.class.getResource("M15F.mp3").toString()));
		this.put("M15P", new Media(SoundLibrary.class.getResource("M15P.mp3").toString()));
		this.put("M15R", new Media(SoundLibrary.class.getResource("M15R.mp3").toString()));
		this.put("M16", new Media(SoundLibrary.class.getResource("M16.mp3").toString()));
		this.put("M16F", new Media(SoundLibrary.class.getResource("M16F.mp3").toString()));
		this.put("M16P", new Media(SoundLibrary.class.getResource("M16P.mp3").toString()));
		this.put("M16R", new Media(SoundLibrary.class.getResource("M16R.mp3").toString()));
		this.put("M17", new Media(SoundLibrary.class.getResource("M17.mp3").toString()));
		this.put("M17F", new Media(SoundLibrary.class.getResource("M17F.mp3").toString()));
		this.put("M17P", new Media(SoundLibrary.class.getResource("M17P.mp3").toString()));
		this.put("M17R", new Media(SoundLibrary.class.getResource("M17R.mp3").toString()));
		this.put("M18", new Media(SoundLibrary.class.getResource("M18.mp3").toString()));
		this.put("M18F", new Media(SoundLibrary.class.getResource("M18F.mp3").toString()));
		this.put("M18P", new Media(SoundLibrary.class.getResource("M18P.mp3").toString()));
		this.put("M18R", new Media(SoundLibrary.class.getResource("M18R.mp3").toString()));
		this.put("M19", new Media(SoundLibrary.class.getResource("M19.mp3").toString()));
		this.put("M19F", new Media(SoundLibrary.class.getResource("M19F.mp3").toString()));
		this.put("M19P", new Media(SoundLibrary.class.getResource("M19P.mp3").toString()));
		this.put("M19R", new Media(SoundLibrary.class.getResource("M19R.mp3").toString()));
		this.put("M20", new Media(SoundLibrary.class.getResource("M20.mp3").toString()));
		this.put("M20F", new Media(SoundLibrary.class.getResource("M20F.mp3").toString()));
		this.put("M20P", new Media(SoundLibrary.class.getResource("M20P.mp3").toString()));
		this.put("M20R", new Media(SoundLibrary.class.getResource("M20R.mp3").toString()));
		this.put("M21", new Media(SoundLibrary.class.getResource("M21.mp3").toString()));
		this.put("M21F", new Media(SoundLibrary.class.getResource("M21F.mp3").toString()));
		this.put("M21P", new Media(SoundLibrary.class.getResource("M21P.mp3").toString()));
		this.put("M21R", new Media(SoundLibrary.class.getResource("M21R.mp3").toString()));
		this.put("MO1R", new Media(SoundLibrary.class.getResource("MO1R.mp3").toString()));
		this.put("P01", new Media(SoundLibrary.class.getResource("P01.mp3").toString()));
		this.put("P01F", new Media(SoundLibrary.class.getResource("P01F.mp3").toString()));
		this.put("P01P", new Media(SoundLibrary.class.getResource("P01P.mp3").toString()));
		this.put("P01R", new Media(SoundLibrary.class.getResource("P01R.mp3").toString()));
		this.put("P02", new Media(SoundLibrary.class.getResource("P02.mp3").toString()));
		this.put("P02F", new Media(SoundLibrary.class.getResource("P02F.mp3").toString()));
		this.put("P02P", new Media(SoundLibrary.class.getResource("P02P.mp3").toString()));
		this.put("P02R", new Media(SoundLibrary.class.getResource("P02R.mp3").toString()));
		this.put("P03", new Media(SoundLibrary.class.getResource("P03.mp3").toString()));
		this.put("P03F", new Media(SoundLibrary.class.getResource("P03F.mp3").toString()));
		this.put("P03P", new Media(SoundLibrary.class.getResource("P03P.mp3").toString()));
		this.put("P03R", new Media(SoundLibrary.class.getResource("P03R.mp3").toString()));
		this.put("P04", new Media(SoundLibrary.class.getResource("P04.mp3").toString()));
		this.put("P04F", new Media(SoundLibrary.class.getResource("P04F.mp3").toString()));
		this.put("P04P", new Media(SoundLibrary.class.getResource("P04P.mp3").toString()));
		this.put("P04R", new Media(SoundLibrary.class.getResource("P04R.mp3").toString()));
		this.put("P05", new Media(SoundLibrary.class.getResource("P05.mp3").toString()));
		this.put("P05F", new Media(SoundLibrary.class.getResource("P05F.mp3").toString()));
		this.put("P05P", new Media(SoundLibrary.class.getResource("P05P.mp3").toString()));
		this.put("P05R", new Media(SoundLibrary.class.getResource("P05R.mp3").toString()));
		this.put("P06", new Media(SoundLibrary.class.getResource("P06.mp3").toString()));
		this.put("P06F", new Media(SoundLibrary.class.getResource("P06F.mp3").toString()));
		this.put("P06P", new Media(SoundLibrary.class.getResource("P06P.mp3").toString()));
		this.put("P06R", new Media(SoundLibrary.class.getResource("P06R.mp3").toString()));
		this.put("P07", new Media(SoundLibrary.class.getResource("P07.mp3").toString()));
		this.put("P07F", new Media(SoundLibrary.class.getResource("P07F.mp3").toString()));
		this.put("P07P", new Media(SoundLibrary.class.getResource("P07P.mp3").toString()));
		this.put("P07R", new Media(SoundLibrary.class.getResource("P07R.mp3").toString()));
		this.put("P08F", new Media(SoundLibrary.class.getResource("P08F.mp3").toString()));
		this.put("P08P", new Media(SoundLibrary.class.getResource("P08P.mp3").toString()));
		this.put("P08R", new Media(SoundLibrary.class.getResource("P08R.mp3").toString()));
		this.put("P09", new Media(SoundLibrary.class.getResource("P09.mp3").toString()));
		this.put("P09F", new Media(SoundLibrary.class.getResource("P09F.mp3").toString()));
		this.put("P09P", new Media(SoundLibrary.class.getResource("P09P.mp3").toString()));
		this.put("P09R", new Media(SoundLibrary.class.getResource("P09R.mp3").toString()));
		this.put("P10", new Media(SoundLibrary.class.getResource("P10.mp3").toString()));
		this.put("P10F", new Media(SoundLibrary.class.getResource("P10F.mp3").toString()));
		this.put("P10P", new Media(SoundLibrary.class.getResource("P10P.mp3").toString()));
		this.put("P10R", new Media(SoundLibrary.class.getResource("P10R.mp3").toString()));
		this.put("P11", new Media(SoundLibrary.class.getResource("P11.mp3").toString()));
		this.put("P11F", new Media(SoundLibrary.class.getResource("P11F.mp3").toString()));
		this.put("P11P", new Media(SoundLibrary.class.getResource("P11P.mp3").toString()));
		this.put("P11R", new Media(SoundLibrary.class.getResource("P11R.mp3").toString()));
		this.put("P12", new Media(SoundLibrary.class.getResource("P12.mp3").toString()));
		this.put("P12F", new Media(SoundLibrary.class.getResource("P12F.mp3").toString()));
		this.put("P12P", new Media(SoundLibrary.class.getResource("P12P.mp3").toString()));
		this.put("P12R", new Media(SoundLibrary.class.getResource("P12R.mp3").toString()));
		this.put("P13", new Media(SoundLibrary.class.getResource("P13.mp3").toString()));
		this.put("P13F", new Media(SoundLibrary.class.getResource("P13F.mp3").toString()));
		this.put("P13P", new Media(SoundLibrary.class.getResource("P13P.mp3").toString()));
		this.put("P13R", new Media(SoundLibrary.class.getResource("P13R.mp3").toString()));
		this.put("P14", new Media(SoundLibrary.class.getResource("P14.mp3").toString()));
		this.put("P14F", new Media(SoundLibrary.class.getResource("P14F.mp3").toString()));
		this.put("P14P", new Media(SoundLibrary.class.getResource("P14P.mp3").toString()));
		this.put("P14R", new Media(SoundLibrary.class.getResource("P14R.mp3").toString()));
		this.put("PO8", new Media(SoundLibrary.class.getResource("PO8.mp3").toString()));
		this.put("R01", new Media(SoundLibrary.class.getResource("R01.mp3").toString()));
		this.put("R02", new Media(SoundLibrary.class.getResource("R02.mp3").toString()));
		this.put("R03", new Media(SoundLibrary.class.getResource("R03.mp3").toString()));
		this.put("R04", new Media(SoundLibrary.class.getResource("R04.mp3").toString()));
		this.put("R05", new Media(SoundLibrary.class.getResource("R05.mp3").toString()));
		this.put("R06", new Media(SoundLibrary.class.getResource("R06.mp3").toString()));
		this.put("R07", new Media(SoundLibrary.class.getResource("R07.mp3").toString()));
		this.put("R08", new Media(SoundLibrary.class.getResource("R08.mp3").toString()));
		this.put("R09", new Media(SoundLibrary.class.getResource("R09.mp3").toString()));
		this.put("R10", new Media(SoundLibrary.class.getResource("R10.mp3").toString()));
		this.put("R11", new Media(SoundLibrary.class.getResource("R11.mp3").toString()));
		this.put("R12", new Media(SoundLibrary.class.getResource("R12.mp3").toString()));
		this.put("R13", new Media(SoundLibrary.class.getResource("R13.mp3").toString()));
		this.put("R14", new Media(SoundLibrary.class.getResource("R14.mp3").toString()));
		this.put("R15", new Media(SoundLibrary.class.getResource("R15.mp3").toString()));
		this.put("R16", new Media(SoundLibrary.class.getResource("R16.mp3").toString()));
		this.put("S01", new Media(SoundLibrary.class.getResource("S01.mp3").toString()));
		this.put("S01F", new Media(SoundLibrary.class.getResource("S01F.mp3").toString()));
		this.put("S01P", new Media(SoundLibrary.class.getResource("S01P.mp3").toString()));
		this.put("S01R", new Media(SoundLibrary.class.getResource("S01R.mp3").toString()));
		this.put("S02", new Media(SoundLibrary.class.getResource("S02.mp3").toString()));
		this.put("S02F", new Media(SoundLibrary.class.getResource("S02F.mp3").toString()));
		this.put("S02P", new Media(SoundLibrary.class.getResource("S02P.mp3").toString()));
		this.put("S02R", new Media(SoundLibrary.class.getResource("S02R.mp3").toString()));
		this.put("S03", new Media(SoundLibrary.class.getResource("S03.mp3").toString()));
		this.put("S03F", new Media(SoundLibrary.class.getResource("S03F.mp3").toString()));
		this.put("S03P", new Media(SoundLibrary.class.getResource("S03P.mp3").toString()));
		this.put("S03R", new Media(SoundLibrary.class.getResource("S03R.mp3").toString()));
		this.put("S04", new Media(SoundLibrary.class.getResource("S04.mp3").toString()));
		this.put("S04F", new Media(SoundLibrary.class.getResource("S04F.mp3").toString()));
		this.put("S04P", new Media(SoundLibrary.class.getResource("S04P.mp3").toString()));
		this.put("S04R", new Media(SoundLibrary.class.getResource("S04R.mp3").toString()));
		this.put("S05", new Media(SoundLibrary.class.getResource("S05.mp3").toString()));
		this.put("S05F", new Media(SoundLibrary.class.getResource("S05F.mp3").toString()));
		this.put("S05P", new Media(SoundLibrary.class.getResource("S05P.mp3").toString()));
		this.put("S05R", new Media(SoundLibrary.class.getResource("S05R.mp3").toString()));
		this.put("S06", new Media(SoundLibrary.class.getResource("S06.mp3").toString()));
		this.put("S06F", new Media(SoundLibrary.class.getResource("S06F.mp3").toString()));
		this.put("S06P", new Media(SoundLibrary.class.getResource("S06P.mp3").toString()));
		this.put("S06R", new Media(SoundLibrary.class.getResource("S06R.mp3").toString()));
		this.put("S07", new Media(SoundLibrary.class.getResource("S07.mp3").toString()));
		this.put("S07F", new Media(SoundLibrary.class.getResource("S07F.mp3").toString()));
		this.put("S07P", new Media(SoundLibrary.class.getResource("S07P.mp3").toString()));
		this.put("S07R", new Media(SoundLibrary.class.getResource("S07R.mp3").toString()));
		this.put("S08", new Media(SoundLibrary.class.getResource("S08.mp3").toString()));
		this.put("S08F", new Media(SoundLibrary.class.getResource("S08F.mp3").toString()));
		this.put("S08P", new Media(SoundLibrary.class.getResource("S08P.mp3").toString()));
		this.put("S08R", new Media(SoundLibrary.class.getResource("S08R.mp3").toString()));
		this.put("S09", new Media(SoundLibrary.class.getResource("S09.mp3").toString()));
		this.put("S09F", new Media(SoundLibrary.class.getResource("S09F.mp3").toString()));
		this.put("S09P", new Media(SoundLibrary.class.getResource("S09P.mp3").toString()));
		this.put("S09R", new Media(SoundLibrary.class.getResource("S09R.mp3").toString()));
		this.put("S10", new Media(SoundLibrary.class.getResource("S10.mp3").toString()));
		this.put("S10F", new Media(SoundLibrary.class.getResource("S10F.mp3").toString()));
		this.put("S10P", new Media(SoundLibrary.class.getResource("S10P.mp3").toString()));
		this.put("S10R", new Media(SoundLibrary.class.getResource("S10R.mp3").toString()));
		this.put("S11", new Media(SoundLibrary.class.getResource("S11.mp3").toString()));
		this.put("S11F", new Media(SoundLibrary.class.getResource("S11F.mp3").toString()));
		this.put("S11P", new Media(SoundLibrary.class.getResource("S11P.mp3").toString()));
		this.put("S11R", new Media(SoundLibrary.class.getResource("S11R.mp3").toString()));
		this.put("S12", new Media(SoundLibrary.class.getResource("S12.mp3").toString()));
		this.put("S12F", new Media(SoundLibrary.class.getResource("S12F.mp3").toString()));
		this.put("S12P", new Media(SoundLibrary.class.getResource("S12P.mp3").toString()));
		this.put("S12R", new Media(SoundLibrary.class.getResource("S12R.mp3").toString()));
		this.put("S13", new Media(SoundLibrary.class.getResource("S13.mp3").toString()));
		this.put("S13F", new Media(SoundLibrary.class.getResource("S13F.mp3").toString()));
		this.put("S13P", new Media(SoundLibrary.class.getResource("S13P.mp3").toString()));
		this.put("S13R", new Media(SoundLibrary.class.getResource("S13R.mp3").toString()));
		this.put("S14", new Media(SoundLibrary.class.getResource("S14.mp3").toString()));
		this.put("S14F", new Media(SoundLibrary.class.getResource("S14F.mp3").toString()));
		this.put("S14P", new Media(SoundLibrary.class.getResource("S14P.mp3").toString()));
		this.put("S14R", new Media(SoundLibrary.class.getResource("S14R.mp3").toString()));
		this.put("U01", new Media(SoundLibrary.class.getResource("U01.mp3").toString()));
		this.put("U02", new Media(SoundLibrary.class.getResource("U02.mp3").toString()));
		this.put("W01", new Media(SoundLibrary.class.getResource("W01.mp3").toString()));
		this.put("W01F", new Media(SoundLibrary.class.getResource("W01F.mp3").toString()));
		this.put("W01P", new Media(SoundLibrary.class.getResource("W01P.mp3").toString()));
		this.put("W01R", new Media(SoundLibrary.class.getResource("W01R.mp3").toString()));
		this.put("W02", new Media(SoundLibrary.class.getResource("W02.mp3").toString()));
		this.put("W02F", new Media(SoundLibrary.class.getResource("W02F.mp3").toString()));
		this.put("W02P", new Media(SoundLibrary.class.getResource("W02P.mp3").toString()));
		this.put("W02R", new Media(SoundLibrary.class.getResource("W02R.mp3").toString()));
		this.put("W03", new Media(SoundLibrary.class.getResource("W03.mp3").toString()));
		this.put("W03F", new Media(SoundLibrary.class.getResource("W03F.mp3").toString()));
		this.put("W03P", new Media(SoundLibrary.class.getResource("W03P.mp3").toString()));
		this.put("W03R", new Media(SoundLibrary.class.getResource("W03R.mp3").toString()));
		this.put("W04", new Media(SoundLibrary.class.getResource("W04.mp3").toString()));
		this.put("W04F", new Media(SoundLibrary.class.getResource("W04F.mp3").toString()));
		this.put("W04P", new Media(SoundLibrary.class.getResource("W04P.mp3").toString()));
		this.put("W04R", new Media(SoundLibrary.class.getResource("W04R.mp3").toString()));
		this.put("W05", new Media(SoundLibrary.class.getResource("W05.mp3").toString()));
		this.put("W05F", new Media(SoundLibrary.class.getResource("W05F.mp3").toString()));
		this.put("W05P", new Media(SoundLibrary.class.getResource("W05P.mp3").toString()));
		this.put("W05R", new Media(SoundLibrary.class.getResource("W05R.mp3").toString()));
		this.put("W06", new Media(SoundLibrary.class.getResource("W06.mp3").toString()));
		this.put("W06F", new Media(SoundLibrary.class.getResource("W06F.mp3").toString()));
		this.put("W06P", new Media(SoundLibrary.class.getResource("W06P.mp3").toString()));
		this.put("W06R", new Media(SoundLibrary.class.getResource("W06R.mp3").toString()));
		this.put("W07", new Media(SoundLibrary.class.getResource("W07.mp3").toString()));
		this.put("W07F", new Media(SoundLibrary.class.getResource("W07F.mp3").toString()));
		this.put("W07P", new Media(SoundLibrary.class.getResource("W07P.mp3").toString()));
		this.put("W07R", new Media(SoundLibrary.class.getResource("W07R.mp3").toString()));
		this.put("W08", new Media(SoundLibrary.class.getResource("W08.mp3").toString()));
		this.put("W08F", new Media(SoundLibrary.class.getResource("W08F.mp3").toString()));
		this.put("W08P", new Media(SoundLibrary.class.getResource("W08P.mp3").toString()));
		this.put("W08R", new Media(SoundLibrary.class.getResource("W08R.mp3").toString()));
		this.put("W09", new Media(SoundLibrary.class.getResource("W09.mp3").toString()));
		this.put("W09F", new Media(SoundLibrary.class.getResource("W09F.mp3").toString()));
		this.put("W09P", new Media(SoundLibrary.class.getResource("W09P.mp3").toString()));
		this.put("W09R", new Media(SoundLibrary.class.getResource("W09R.mp3").toString()));
		this.put("W10", new Media(SoundLibrary.class.getResource("W10.mp3").toString()));
		this.put("W10F", new Media(SoundLibrary.class.getResource("W10F.mp3").toString()));
		this.put("W10P", new Media(SoundLibrary.class.getResource("W10P.mp3").toString()));
		this.put("W10R", new Media(SoundLibrary.class.getResource("W10R.mp3").toString()));
		this.put("W11", new Media(SoundLibrary.class.getResource("W11.mp3").toString()));
		this.put("W11F", new Media(SoundLibrary.class.getResource("W11F.mp3").toString()));
		this.put("W11P", new Media(SoundLibrary.class.getResource("W11P.mp3").toString()));
		this.put("W11R", new Media(SoundLibrary.class.getResource("W11R.mp3").toString()));
		this.put("W12", new Media(SoundLibrary.class.getResource("W12.mp3").toString()));
		this.put("W12F", new Media(SoundLibrary.class.getResource("W12F.mp3").toString()));
		this.put("W12P", new Media(SoundLibrary.class.getResource("W12P.mp3").toString()));
		this.put("W12R", new Media(SoundLibrary.class.getResource("W12R.mp3").toString()));
		this.put("W13", new Media(SoundLibrary.class.getResource("W13.mp3").toString()));
		this.put("W13F", new Media(SoundLibrary.class.getResource("W13F.mp3").toString()));
		this.put("W13P", new Media(SoundLibrary.class.getResource("W13P.mp3").toString()));
		this.put("W13R", new Media(SoundLibrary.class.getResource("W13R.mp3").toString()));
		this.put("W14", new Media(SoundLibrary.class.getResource("W14.mp3").toString()));
		this.put("W14F", new Media(SoundLibrary.class.getResource("W14F.mp3").toString()));
		this.put("W14P", new Media(SoundLibrary.class.getResource("W14P.mp3").toString()));
		this.put("W14R", new Media(SoundLibrary.class.getResource("W14R.mp3").toString()));
	}
	
	public MediaPlayer getPlayerFor(String cardId) {
		try {
			return new MediaPlayer(this.get(cardId));
		} catch (Exception e) {
			System.out.println("Error creating media, resources? Providing fallback.");
			return fallback;
		}
	}
	
	public MediaPlayer getPlayerFor(Card card, Position position) {
		return getPlayerFor(card.cardId(), position);
	}

	public MediaPlayer getPlayerFor(String cardId, Position position) {
		return new MediaPlayer(switch (position) {
			case PAST -> get(cardId + "P");
			case PRESENT -> get(cardId + "R");
			case FUTURE -> get(cardId + "F");
		});
	}
}
