package org.overworld.tarotbooth.model;

import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.stereotype.Component;

@Component
public class Deck extends HashMap<String, Deck.Card> {

	private static final long serialVersionUID = -8299688802942289003L;

	public enum Positivity {
		VERY_POSITIVE, POSITIVE, NEUTRAL, NEGATIVE, VERY_NEGATIVE
	}

	public static record Card(String cardId, String filename, String rfcId, String name, String drawAudio,
			String pastAudio, String presentAudio, String futureAudio, String pastText, String presentText,
			String futureText, Positivity positivity) {
	};

	private Map<String, String> nfcIdToCardId;
	
	public Card lookupByNfcId(String nfcId) {
		return this.get(nfcIdToCardId.get(nfcId));
	}
	
	{
		/* @formatter:off */
		this.put("C01", new Card("C01", "C01.png", "1de2996a031080", "Ace of Cups", "C01.mp3", "C01P.mp3", "C01R.mp3", "C01F.mp3", "You have found new love or a stirring of passions.", "You are experiencing new love or happiness or a stirring of passions.", "You will experience new love or happiness or a stirring of passions.", Positivity.POSITIVE));
		this.put("C02", new Card("C02", "C02.png", "1d819c6a031080", "Two of Cups", "C02.mp3", "C02P.mp3", "C02R.mp3", "C02F.mp3", "You have enjoyed a happy union, romance or affair.", "You are experiencing a happy union, romance or affair.", "You will experience a happy union, romance or affair.", Positivity.POSITIVE));
		this.put("C03", new Card("C03", "C03.png", "1df5996a031080", "Three of Cups", "C03.mp3", "C03P.mp3", "C03R.mp3", "C03F.mp3", "You have had a celebration, reunion or joyful occasion.", "You are having a celebration, reunion or joyful occasion.", "You will have a celebration, reunion or joyful occasion.", Positivity.POSITIVE));
		this.put("C04", new Card("C04", "C04.png", "1de1996a031080", "Four of Cups", "C04.mp3", "C04P.mp3", "C04R.mp3", "C04F.mp3", "You have experienced a period dissatisfaction, boredom and discontent. You may have been unable to see your advantages because you focused on the negative.", "You are experiencing dissatisfaction, boredom and discontent. You cannot see the good things in your life because you are blinded by the negative.", "You will experience dissatisfaction, boredom and discontent Be careful you don’t get blinded by the negative and loose sight of the good things in your life.", Positivity.NEGATIVE));
		this.put("C05", new Card("C05", "C05.png", "1d92996a031080", "Five of Cups", "C05.mp3", "C05P.mp3", "C05R.mp3", "C05F.mp3", "You have experienced loss and disappointment, sadness or mourning.", "You are experiencing loss and disappointment, sadness or mourning.", "You will experience loss and disappointment, sadness or mourning. Have another tarot reading soon.", Positivity.VERY_NEGATIVE));
		this.put("C06", new Card("C06", "C06.png", "1ded9c6a031080", "Six of Cups", "C06.mp3", "C06P.mp3", "C06R.mp3", "C06F.mp3", "You have experienced a period of innocence, nostalgia or reliving the past.", "You are reliving the past or experiencing nostalgia or innocence.", "You will enter a period of nostalgia where you relive the past and experience fond memories or innocence.", Positivity.POSITIVE));
		this.put("C07", new Card("C07", "C07.png", "1da0996a031080", "Seven of Cups", "C07.mp3", "C07P.mp3", "C07R.mp3", "C07F.mp3", "You have been daydreaming or living in a state of confusion or overwhelm.", "You are daydreaming or living in a state of confusion or overwhelm.", "You will enter a period of daydreaming  where you will experience confusion and overwhelm.", Positivity.NEGATIVE));
		this.put("C08", new Card("C08", "C08.png", "1dfe996a031080", "Eight of Cups", "C08.mp3", "C08P.mp3", "C08R.mp3", "C08F.mp3", "You have had a change of heart and  have begun moving on.", "You are having a change of heart and have begun moving on.", "You will have a change of heart requiring you to move on.", Positivity.NEGATIVE));
		this.put("C09", new Card("C09", "C09.png", "1def9c6a031080", "Nine of Cups", "C09.mp3", "C09P.mp3", "C09R.mp3", "C09F.mp3", "Your wishes have been fulfilled.", "Your wishes are fulfilled at this time.", "Your wishes will shortly be fulfilled.", Positivity.POSITIVE));
		this.put("C10", new Card("C10", "C10.png", "1d22996a031080", "Ten of Cups", "C10.mp3", "C10P.mp3", "C10R.mp3", "C10F.mp3", "You have enjoyed harmony in your interpersonal relationships.", "You are enjoying harmony in your interpersonal relationships.", "You will enjoy harmony in your interpersonal relationships.", Positivity.POSITIVE));
		this.put("C11", new Card("C11", "C11.png", "1d9b996a031080", "Page of Cups", "C11.mp3", "C11P.mp3", "C11R.mp3", "C11F.mp3", "You have received an invitation or overture of friendship. You may have experienced increased sensitivity or met a young affectionate person.", "You are in receipt of an invitation to a friendship or social event. You may be feeling sensitive or may know a sensitive young person who has influence on your situation.", "You will receive an invitation or somebody will make friends with you. You may feel sensitive or make friends with a assistive person.", Positivity.POSITIVE));
		this.put("C12", new Card("C12", "C12.png", "1dfd996a031080", "Knight of Cups", "C12.mp3", "C12P.mp3", "C12R.mp3", "C12F.mp3", "You have started a new relationship, romance or artistic endeavour. You may have met a romantic or idealistic young man.", "You are starting a new relationship, romance or artistic endeavour. You may know a romantic or idealistic young man who has bearing on your situation.", "You will start a new relationship, romance or artistic endeavour. You may meet a romantic or idealistic young man who will have bearing on your situation.", Positivity.POSITIVE));
		this.put("C13", new Card("C13", "C13.png", "1de49c6a031080", "Queen of Cups", "C13.mp3", "C13P.mp3", "C13R.mp3", "C13F.mp3", "You have experienced deep nurturing feelings. You may have met a motherly figure.", "You are experiencing deep nurturing feelings. You may know a motherly figure who has bearing on your situation.", "You will experience deep nurturing feelings. You may meet a motherly figure who has bearing on your situation.", Positivity.POSITIVE));
		this.put("C14", new Card("C14", "C14.png", "1de39c6a031080", "King of Cups", "C14.mp3", "C14P.mp3", "C14R.mp3", "C14F.mp3", "You have received or required wise counsel. You may have met a wise and emotionally intelligent man.", "You are receiving or you require wise counsel. You may know a wise and emotionally intelligent man who can help you.", "You will benefit from wise counsel. You may meet a wise and emotionally intelligent man who can help you.", Positivity.POSITIVE));
		this.put("M00", new Card("M00", "M00.png", "1d829c6a031080", "The Fool", "M00.mp3", "M00P.mp3", "M00R.mp3", "M00F.mp3", "There has been a new start and a new injection of energy. A new journey has begun.", "You are getting a fresh start. A new exciting journey is beginning that relates to your question.", "You will embark upon an exciting journey. A fresh start relating to your question will come soon.", Positivity.VERY_POSITIVE));
		this.put("M01", new Card("M01", "M01.png", "1d9c996a031080", "The Magician", "M01.mp3", "M01P.mp3", "M01R.mp3", "M01F.mp3", "You or another actor have exerted professional influence, expertise or mastery upon the situation.", "You or another actor is exerting professional influence, expertise or mastery upon the situation.", "You or another actor will exert professional influence, expertise or mastery upon the situation.", Positivity.POSITIVE));
		this.put("M02", new Card("M02", "M02.png", "1d9d996a031080", "The High Priestess", "M02.mp3", "M02P.mp3", "M02R.mp3", "M02F.mp3", "A strong spiritual and morally correct influence has informed the situation. There has been a spiritual looking within.", "A strong spiritual and morally correct influence is informing the situation. There is a spiritual looking within.", "A strong spiritual and morally correct influence will inform the situation. There will be a spiritual looking within.", Positivity.POSITIVE));
		this.put("M03", new Card("M03", "M03.png", "1da1996a031080", "The Empress", "M03.mp3", "M03P.mp3", "M03R.mp3", "M03F.mp3", "The power of abundance, healing and new life has informed the current situation.", "The power of abundance, healing and new life is informing the current situation.", "The power of abundance, healing and new life will inform the current situation.", Positivity.POSITIVE));
		this.put("M04", new Card("M04", "M04.png", "1da5996a031080", "The Emperor", "M04.mp3", "M04P.mp3", "M04R.mp3", "M04F.mp3", "An adult, masculine power has influenced the situation.", "An adult, masculine power is influencing the situation.", "An adult, masculine power will influence the situation.", Positivity.POSITIVE));
		this.put("M05", new Card("M05", "M05.png", "1d25996a031080", "The Hierophant", "M05.mp3", "M05P.mp3", "M05R.mp3", "M05F.mp3", "Conventional wisdom, orthodoxy and ritual have affected the situation.", "Conventional wisdom, orthodoxy and ritual is affecting the situation.", "Conventional wisdom, orthodoxy and ritual will affect the situation.", Positivity.NEUTRAL));
		this.put("M06", new Card("M06", "M06.png", "1dff996a031080", "The Lovers", "M06.mp3", "M06P.mp3", "M06R.mp3", "M06F.mp3", "The power of union, sharing, trust and choice influenced the situation", "The power of union, sharing, trust and choice is influencing the situation", "The power of union, sharing and trust will influence the situation", Positivity.VERY_POSITIVE));
		this.put("M07", new Card("M07", "M07.png", "1d9a996a031080", "The Chariot", "M07.mp3", "M07P.mp3", "M07R.mp3", "M07F.mp3", "There has been a clear decisive purpose that has harnessed opposing forces to progress the current situation.", "There is a clear decisive purpose that is harnessing opposing forces to progress the current situation.", "There will be a clear decisive purpose to harness opposing forces and progress the current situation.", Positivity.POSITIVE));
		this.put("M08", new Card("M08", "M08.png", "1d7f9c6a031080", "Strength", "M08.mp3", "M08P.mp3", "M08R.mp3", "M08F.mp3", "Inner strength and conviction have progressed the current situation.", "Inner strength and conviction are progressing the current situation.", "Inner strength and conviction will progress the current situation.", Positivity.VERY_POSITIVE));
		this.put("M09", new Card("M09", "M09.png", "1d93996a031080", "The Hermit", "M09.mp3", "M09P.mp3", "M09R.mp3", "M09F.mp3", "Self-discovery, meditation and a journey within have influenced the current situation,", "Self-discovery, meditation and a journey within is occurring or is required at this time.", "Self-discovery, meditation and a journey within is necessary.", Positivity.POSITIVE));
		this.put("M10", new Card("M10", "M10.png", "1de99c6a031080", "Wheel of Fortune", "M10.mp3", "M10P.mp3", "M10R.mp3", "M10F.mp3", "There has been some good luck. An upturn of fate on the sea of fortune has benefited you.", "Good luck is presenting. An upturn of fate on the sea of fortune is benefiting you.", "There will be some good luck. An upturn of fate on the sea of fortune will benefit you.", Positivity.VERY_POSITIVE));
		this.put("M11", new Card("M11", "M11.png", "1d98996a031080", "Justice", "M11.mp3", "M11P.mp3", "M11R.mp3", "M11F.mp3", "Harmony, fairness and integrity have prompted a situation. There may have been a legal issue.", "Harmony, fairness and integrity, morality and strategy are at play. The law is on your side.", "Harmony, fairness and integrity, morality and strategy will benefit you. You will get what you deserve.", Positivity.POSITIVE));
		this.put("M12", new Card("M12", "M12.png", "1d23996a031080", "The Hanged Man", "M12.mp3", "M12P.mp3", "M12R.mp3", "M12F.mp3", "There has been a delay or a new perspective. Self-sacrifice may have occurred.", "You are in a state of suspension and patience is required. You are gaining a new perspective.", "There will be a delay. You will gain a new perspective from waiting until a more suitable time.", Positivity.NEUTRAL));
		this.put("M13", new Card("M13", "M13.png", "1da2996a031080", "Death", "M13.mp3", "M13P.mp3", "M13R.mp3", "M13F.mp3", "There has been a potent change or cessation.", "A powerful change is afoot.", "There will be a sudden and radical change", Positivity.NEGATIVE));
		this.put("M14", new Card("M14", "M14.png", "1d009a6a031080", "Temperance", "M14.mp3", "M14P.mp3", "M14R.mp3", "M14F.mp3", "There has been moderation and self-restraint.", "Now is the time for moderation and self-restraint.", "Moderation and self-restraint will be required.", Positivity.NEUTRAL));
		this.put("M15", new Card("M15", "M15.png", "1df4996a031080", "The Devil", "M15.mp3", "M15P.mp3", "M15R.mp3", "M15F.mp3", "You have suffered from self-limiting beliefs and self-sabotaging actions. You have nobody to blame but yourself.", "You are suffering from self-limiting beliefs and self-sabotaging actions. You have nobody to blame but yourself, though you can choose a better course.", "You will suffer from self-limiting beliefs and self-sabotaging actions. You must be strong and objective and choose a better way.", Positivity.NEGATIVE));
		this.put("M16", new Card("M16", "M16.png", "1d7e9c6a031080", "The Tower", "M16.mp3", "M16P.mp3", "M16R.mp3", "M16F.mp3", "There has been the sudden collapse of a structure or institution.", "A structure or institution is collapsing. A deeply-ingrained pattern is unraveling.", "A structure or institution will collapse. Deeply ingrained patterns will change as a result. Hang on tight!", Positivity.NEGATIVE));
		this.put("M17", new Card("M17", "M17.png", "1dec9c6a031080", "The Star", "M17.mp3", "M17P.mp3", "M17R.mp3", "M17F.mp3", "Great inspiration, hope, luck and optimism have influenced your current situation.", "There is currently great optimism, luck, tranquility and trust are present right now.", "A time of great hope and optimism is coming.", Positivity.VERY_POSITIVE));
		this.put("M18", new Card("M18", "M18.png", "1df6996a031080", "The Moon", "M18.mp3", "M18P.mp3", "M18R.mp3", "M18F.mp3", "Deep instinctual forces, concealment, occlusion, passivity and self-deception have weighed on the situation.", "Deep instinctual forces, concealment, occlusion, passivity and self-deception are weighing on the situation.", "Deep instinctual forces, concealment, occlusion, passivity and self-deception will weigh on the situation. Intuition from other worlds may present.", Positivity.NEGATIVE));
		this.put("M19", new Card("M19", "M19.png", "1de59c6a031080", "The Sun", "M19.mp3", "M19P.mp3", "M19R.mp3", "M19F.mp3", "There has been great success and fulfillment.", "Great success and fulfillment are afoot.", "There will be great success, fulfillment, reward and vitality.", Positivity.VERY_POSITIVE));
		this.put("M20", new Card("M20", "M20.png", "1d9e996a031080", "Judgment", "M20.mp3", "M20P.mp3", "M20R.mp3", "M20F.mp3", "A situation came to an end and a judgment or evaluation was made.", "A situation is nearing its end and it is time to make an evaluation of it. A choice is being made.", "A situation will end soon. There will be an evaluation and possibly a choice.", Positivity.POSITIVE));
		this.put("M21", new Card("M21", "M21.png", "1d9f996a031080", "The World", "M21.mp3", "M21P.mp3", "M21R.mp3", "M21F.mp3", "A situation came to a complete end. A goal was achieved. The querent is liberated.", "A situation is ending and liberation is attained. The end of one cycle clears way for a fresh start.", "A situation will come to an end soon. Freedom and liberation will result.", Positivity.POSITIVE));
		this.put("P01", new Card("P01", "P01.png", "1d95996a031080", "Ace of Pentacles", "P01.mp3", "P01P.mp3", "P01R.mp3", "P01F.mp3", "You had a windfall or some good luck leading to comfort or new beginnings.", "You are enjoying a period of good luck that will bring you comfort and prosperity.", "You will have some good luck or a windfall bringing renewed prosperity.", Positivity.POSITIVE));
		this.put("P02", new Card("P02", "P02.png", "1d799c6a031080", "Two of Pentacles", "P02.mp3", "P02P.mp3", "P02R.mp3", "P02F.mp3", "You have endured a period of balancing finances carefully.", "You are experiencing a challenge balancing the demands placed on you.", "You will experience a period where balance is important and may cause stress.", Positivity.NEGATIVE));
		this.put("P03", new Card("P03", "P03.png", "1d839c6a031080", "Three of Pentacles", "P03.mp3", "P03P.mp3", "P03R.mp3", "P03F.mp3", "You have applied your talents to best effect and done a good job.", "You are doing a great job and applying your talents effectively.", "You will be in a position to do an excellent job. Be sure to apply your telnets carefully to reap the rewards.", Positivity.NEUTRAL));
		this.put("P04", new Card("P04", "P04.png", "1d019a6a031080", "Four of Pentacles", "P04.mp3", "P04P.mp3", "P04R.mp3", "P04F.mp3", "You have experienced a period of holding tight or standing still.", "You are holding tight for gain or preservation. It may be to your advantage but likely doesn’t feel good.", "You will be forced to hold on tight to get what you want.", Positivity.NEGATIVE));
		this.put("P05", new Card("P05", "P05.png", "1dfb996a031080", "Five of Pentacles", "P05.mp3", "P05P.mp3", "P05R.mp3", "P05F.mp3", "You have experienced a period of financial or spiritual poverty and desperation.", "You are experiencing a period of poverty and desperation.", "A period of lack, poverty or despair may befall you. You should have another tarot reading soon.", Positivity.NEGATIVE));
		this.put("P06", new Card("P06", "P06.png", "1df09c6a031080",  "Six of Pentacles", "P06.mp3", "P06P.mp3", "P06R.mp3", "P06F.mp3", "You have come through a period of give and take where generosity played a part in your experience.", "You may need to be generous or rely on the generosity of others, or both, at this time.", "You are entering a time where generosity will be important. You may need to be generous or accept the generosity of others.", Positivity.NEUTRAL));
		this.put("P07", new Card("P07", "P07.png", "1df3996a031080", "Seven of Pentacles", "P07.mp3", "P07P.mp3", "P07R.mp3", "P07F.mp3", "You have been patient and tended your garden which has led to rewards accumulating for you.", "You must be patient and tend your garden. Rewards will accrue from your perseverance.", "You will exhibit patience and reap great rewards from your perseverance.", Positivity.NEUTRAL));
		this.put("P08", new Card("P08", "P08.png", "1d7a9c6a031080", "Eight of Pentacles", "P08.mp3", "P08P.mp3", "P08R.mp3", "P08F.mp3", "You have enjoyed an apprenticeship and acquired skills and motivation to use your talents well.", "You are enjoying an apprenticeship and acquiring skills and motivation to use your talents well.", "You will enter an apprenticeship or period of learning new skills.", Positivity.NEUTRAL));
		this.put("P09", new Card("P09", "P09.png", "1dfa996a031080", "Nine of Pentacles", "P09.mp3", "P09P.mp3", "P09R.mp3", "P09F.mp3", "You have been self-reliant in spiritual, life and financial affairs. This self-reliance has been important to you.", "You are very self-sufficient and are enjoying prosperity and success as a result.", "You will be required to be self-sufficient to care for your life, financial and spiritual needs.", Positivity.NEUTRAL));
		this.put("P10", new Card("P10", "P10.png", "1de19c6a031080", "Ten of Pentacles", "P10.mp3", "P10P.mp3", "P10R.mp3", "P10F.mp3", "You have enjoyed significant support and comfort from your family affairs bringing wealth and security.", "You are enjoying significant support and comfort from your family affairs bringing wealth and security.", "You will enjoy significant support and comfort from your family affairs bringing wealth and security.", Positivity.POSITIVE));
		this.put("P11", new Card("P11", "P11.png", "1deb9c6a031080", "Page of Pentacles", "P11.mp3", "P11P.mp3", "P11R.mp3", "P11F.mp3", "You have enjoyed a small financial gain or learned a lesson. You may have met a young person who is financially wise and reflective.", "You are learning a lesson and may be receiving a small financial gain. You may know a young, financially wise and reflective person who helps you.", "You may learn a lesson or receive a small financial gain. You may meet a young, financially wise and reflective person.", Positivity.POSITIVE));
		this.put("P12", new Card("P12", "P12.png", "1da3996a031080", "Knight of Pentacles", "P12.mp3", "P12P.mp3", "P12R.mp3", "P12F.mp3", "You have made steady and tangible progress. You may have met a conscientious, dependable person.", "You are making steady and tangible progress in life and finances. You may know a conscientious, dependable person who helps you.", "You will make steady and tangible progress in life and finances. You may meet a conscientious, dependable person who helps you.", Positivity.POSITIVE));
		this.put("P13", new Card("P13", "P13.png", "1df2996a031080", "Queen of Pentacles", "P13.mp3", "P13P.mp3", "P13R.mp3", "P13F.mp3", "You have taken a sensible approach. You may have met a businesswoman who helped you.", "You are taking a sensible approach. You may know a shrewd businesswoman who helps you.", "You are going to take a sensible approach. You may meet a shrewd businesswoman to help you.", Positivity.POSITIVE));
		this.put("P14", new Card("P14", "P14.png", "1d94996a031080", "King of Pentacles", "P14.mp3", "P14P.mp3", "P14R.mp3", "P14F.mp3", "You have enjoyed shrewd , practical business dealings. You may have met a wise businessman who helped you.", "You are enjoying a period of shrewd, practical dealings in life and business, you may know a wise businessman who helps you.", "You will enjoy a period of shrewd, practical dealings in life and business, you may meet a wise businessman who helps you.", Positivity.POSITIVE));
		this.put("S01", new Card("S01", "S01.png", "1d99996a031080", "Ace of Swords", "S01.mp3", "S01P.mp3", "S01R.mp3", "S01F.mp3", "You have enjoyed an infusion of strength which may have helped you in adversity.", "You are enjoying renewed strength in the face of adversity. You are determined and courageous at this time.", "You will enjoy renewed strength in the face of adversity. You will be determined and courageous.", Positivity.POSITIVE));
		this.put("S02", new Card("S02", "S02.png", "1d21996a031080", "Two of Swords", "S02.mp3", "S02P.mp3", "S02R.mp3", "S02F.mp3", "You experienced a stalemate or impasse where your energies and experiences were stuck.", "You are stuck in an experience of stalemate or impasse.", "You will experience a period of stalemate, impasse or frustration.", Positivity.NEGATIVE));
		this.put("S03", new Card("S03", "S03.png", "1d7b9c6a031080", "Three of Swords", "S03.mp3", "S03P.mp3", "S03R.mp3", "S03F.mp3", "You have gone through a period of heartache, loss or woe. It was likely necessary for your growth.", "You are going through a period of heartache, loss or woe. It is likely necessary for your growth.", "Batten down the hatches! You will experience a period of heartache. You should have another tarot reading soon.", Positivity.VERY_NEGATIVE));
		this.put("S04", new Card("S04", "S04.png", "1df39c6a031080", "Four of Swords", "S04.mp3", "S04P.mp3", "S04R.mp3", "S04F.mp3", "You have had a well-deserved rest.", "You are enjoying a period of well-deserved rest. Make the most of it!", "You will enjoy a period of well-deserved rest. Make the most of it!", Positivity.POSITIVE));
		this.put("S05", new Card("S05", "S05.png", "1df29c6a031080", "Five of Swords", "S05.mp3", "S05P.mp3", "S05R.mp3", "S05F.mp3", "You experienced jealousy and one-upmanship, humiliation and wounded pride or you inflicted it on another.", "You are entwined in a game of one-upmanship. Wounded pride and humiliation are not far behind.", "You will get entwined in a game of one-upmanship. Wounded pride and humiliation are not far behind.", Positivity.NEGATIVE));
		this.put("S06", new Card("S06", "S06.png", "1da4996a031080", "Six of Swords", "S06.mp3", "S06P.mp3", "S06R.mp3", "S06F.mp3", "You have started enjoying brighter times and maybe a reconciliation.", "You are enjoying brighter times and maybe a reconciliation.", "You will enjoy brighter times and maybe a reconciliation.", Positivity.POSITIVE));
		this.put("S07", new Card("S07", "S07.png", "1de89c6a031080", "Seven of Swords", "S07.mp3", "S07P.mp3", "S07R.mp3", "S07F.mp3", "You experienced stealth or a display of the unexpected. You may have committed or experienced trickery", "You are experiencing stealth or a display of the unexpected. You may be committing or experiencing trickery", "You will experience stealth or a display of the unexpected. You may commit or experience trickery", Positivity.NEGATIVE));
		this.put("S08", new Card("S08", "S08.png", "1dee9c6a031080", "Eight of Swords", "S08.mp3", "S08P.mp3", "S08R.mp3", "S08F.mp3", "You were trapped in an oppressive situation ", "You are trapped in an oppressive situation, holding a defensive perimeter.", "You will be trapped in an oppressive situation, holding a defensive perimeter.", Positivity.VERY_NEGATIVE));
		this.put("S09", new Card("S09", "S09.png", "1df7996a031080", "Nine of Swords", "S09.mp3", "S09P.mp3", "S09R.mp3", "S09F.mp3", "You have experienced a period of despair that was troubling but may have seemed worse than it was.", "You are experiencing a period of despair that is troubling but may, like a nightmare, be unreal.", "You will experience a period of despair that is troubling but may, like a nightmare, be unreal.", Positivity.VERY_NEGATIVE));
		this.put("S10", new Card("S10", "S10.png", "1df69c6a031080", "Ten of Swords", "S10.mp3", "S10P.mp3", "S10R.mp3", "S10F.mp3", "There has been an irrevocable ending. You can’t do anything about it. The situation is not reversible but a new dawn is coming soon.", "You are experiencing an irrevocable ending. You can’t do anything about it, The situation is not reversible but a new dawn is coming soon.", "You will experience an irrevocable ending. Once over, the situation is not reversible but a new dawn will come soon after", Positivity.NEUTRAL));
		this.put("S11", new Card("S11", "S11.png", "1df19c6a031080", "Page of Swords", "S11.mp3", "S11P.mp3", "S11R.mp3", "S11F.mp3", "You may have had bad news or a met a person who is cold, clinical, precocious and decisive.", "You may be experiencing bad news or a know a person who is cold, clinical, precocious and decisive who will affect your circumstances.", "You may experience bad news or a meet a person who is cold, clinical, precocious and decisive who will affect your circumstances.", Positivity.NEGATIVE));
		this.put("S12", new Card("S12", "S12.png", "1dfc996a031080", "Knight of Swords", "S12.mp3", "S12P.mp3", "S12R.mp3", "S12F.mp3", "You have experienced blunt communication, or swift and sudden change. You may have met a strong, assertive leader.", "You are experiencing blunt communication, or swift and sudden change. You may know a strong, assertive leader to guide you.", "You will experience blunt communication, or swift and sudden change. You may meet a strong, assertive leader to guide you.", Positivity.NEGATIVE));
		this.put("S13", new Card("S13", "S13.png", "1d7d9c6a031080", "Queen of Swords", "S13.mp3", "S13P.mp3", "S13R.mp3", "S13F.mp3", "You have experienced  solitude which gave you time to think rationally. You may have met a strong, analytical and aloof woman.", "You are experiencing  solitude which gives you time to think rationally. You may know a strong, analytical and aloof woman.", "You will experience  solitude which gives you time to think rationally. You may meet a strong, analytical and aloof woman.", Positivity.NEGATIVE));
		this.put("S14", new Card("S14", "S14.png", "1de69c6a031080", "King of Swords", "S14.mp3", "S14P.mp3", "S14R.mp3", "S14F.mp3", "You experienced authority and command  without emotion. You may have met a man who is cold and authoritative.", "You are experiencing authority and command  without emotion. You may know a man who is cold and authoritative who is affecting your situation.", "You will experience authority and command  without emotion. You may meet a man who is cold and authoritative who affects your situation..", Positivity.NEGATIVE));
		this.put("W01", new Card("W01", "W01.png", "1df8996a031080", "Ace of Wands", "W01.mp3", "W01P.mp3", "W01R.mp3", "W01F.mp3", "New inspirations and vitality have influenced the situation.", "New inspiration, vitality, a new venture or enterprise are afoot.", "There will be a new venture or enterprise accompanied by renewed inspiration and vitality.", Positivity.POSITIVE));
		this.put("W02", new Card("W02", "W02.png", "1de29c6a031080", "Two of Wands", "W02.mp3", "W02P.mp3", "W02R.mp3", "W02F.mp3", "A great opportunity befell you.", "A great opportunity is presenting. An adventure is off to a good, but early, start.", "There will be an opportunity for a new venture or adventure.", Positivity.POSITIVE));
		this.put("W03", new Card("W03", "W03.png", "1df59c6a031080", "Three of Wands", "W03.mp3", "W03P.mp3", "W03R.mp3", "W03F.mp3", "An enterprise has successfully begun.", "An enterprise is beginning.", "An enterprise will begin.", Positivity.POSITIVE));
		this.put("W04", new Card("W04", "W04.png", "1de79c6a031080", "Four of Wands", "W04.mp3", "W04P.mp3", "W04R.mp3", "W04F.mp3", "You have enjoyed a haven of refuge where you belonged and were comfortable.", "You are enjoying a haven of refuge where you belong and are comfortable.", "You will enjoy a haven of refuge where you belong and feel comfortable.", Positivity.NEUTRAL));
		this.put("W05", new Card("W05", "W05.png", "1d809c6a031080", "Five of Wands", "W05.mp3", "W05P.mp3", "W05R.mp3", "W05F.mp3", "There was an exciting exchange or challenge.", "An exciting exchange, competition or challenge is afoot.", "There will be an exciting exchange, competition or challenge.", Positivity.NEGATIVE));
		this.put("W06", new Card("W06", "W06.png", "1df89c6a031080", "Six of Wands", "W06.mp3", "W06P.mp3", "W06R.mp3", "W06F.mp3", "You enjoyed a victory.", "You are enjoying a victory or the likelihood of success is high.", "The likelihood of succeeding is very high. You will enjoy a victory.", Positivity.POSITIVE));
		this.put("W07", new Card("W07", "W07.png", "1d96996a031080", "Seven of Wands", "W07.mp3", "W07P.mp3", "W07R.mp3", "W07F.mp3", "You held your own from a position of advantage.", "You are holding your own from a position of advantage.", "You will be required to defend your position however you have the advantage.", Positivity.NEGATIVE));
		this.put("W08", new Card("W08", "W08.png", "1dea9c6a031080", "Eight of Wands", "W08.mp3", "W08P.mp3", "W08R.mp3", "W08F.mp3", "There was a period of very fast movement and change.", "Everything is moving very fast, things will happen quickly now.", "There will be a period of very fast movement, energy and change.", Positivity.POSITIVE));
		this.put("W09", new Card("W09", "W09.png", "1df79c6a031080", "Nine of Wands", "W09.mp3", "W09P.mp3", "W09R.mp3", "W09F.mp3", "You had to stand up for yourself against an attack.", "You are under attack and must stand up for yourself.", "You will be the subject of an attack and must stand up for yourself.", Positivity.NEGATIVE));
		this.put("W10", new Card("W10", "W10.png", "1df49c6a031080", "Ten of Wands", "W10.mp3", "W10P.mp3", "W10R.mp3", "W10F.mp3", "You have carried a heavy load and worked hard but success was a burden not a joy.", "You are carrying too much or working too hard and the burden of success is great.", "You are at risk of working too hard and finding the burden of success too great.", Positivity.NEUTRAL));
		this.put("W11", new Card("W11", "W11.png", "1df9996a031080", "Page of Wands", "W11.mp3", "W11P.mp3", "W11R.mp3", "W11F.mp3", "There was a period of daring action and possibly good news. You may have met a daring and courageous person.", "This is a time of daring action and good news. You may know a person who is daring and courageous.", "Aa time of daring and good news. You may meet a person who is daring and courageous.", Positivity.POSITIVE));
		this.put("W12", new Card("W12", "W12.png", "1d24996a031080", "Knight of Wands", "W12.mp3", "W12P.mp3", "W12R.mp3", "W12F.mp3", "There was a change in your life circumstances. You may have met a person with creative energy who brought or is bringing change.", "A change is afoot in your life circumstances. You may know a person who is creative and brings change.", "There will be a change in your life circumstances You may meet a creative person who brings sudden change.", Positivity.NEUTRAL));
		this.put("W13", new Card("W13", "W13.png", "1d97996a031080", "Queen of Wands", "W13.mp3", "W13P.mp3", "W13R.mp3", "W13F.mp3", "You have enjoyed balanced life, family and career interests. You may have met an attractive, magnetic and powerful woman.", "You are enjoying balanced life, family and career interests. You may know an attractive, magnetic, powerful woman.", "You will enjoy new balance of life, career and family. You may meet an attractive, magnetic woman.", Positivity.POSITIVE));
		this.put("W14", new Card("W14", "W14.png", "1d029a6a031080", "King of Wands", "W14.mp3", "W14P.mp3", "W14R.mp3", "W14F.mp3", "You have enjoyed motivation, maturity and strength. You may have met a strong man.", "You are enjoying motivation, maturity and strength. You may know a strong man who helps you at this time.", "You will enjoy a period of motivation, maturity and strength. You may meet a strong man who assists you.", Positivity.POSITIVE));
		/* @formatter:on */
		
		this.values().parallelStream().forEach(c -> {
			this.replace(c.cardId, new Card(c.cardId, c.filename, Math.random() + "", c.name(), null, null, null, null, null, null, null, null));
		}); //TODO Remove
		
		this.replace("C01", new Card("C01", "C01.png", "12345678901234567890present", "Ace of Cups", null, null, null, null, null, null, null, null));
		
		nfcIdToCardId = this.values().stream().collect(Collectors.toMap(Card::rfcId, Card::cardId));
	}
}
