package org.overworld.tarotbooth.printer;

public enum PrinterStatus {

	OFFLINE, PAPER_OUT, PAPER_LOW, COVER_OPEN, INK_OUT, INK_LOW, AUTOCUTTER_ERROR, UNRECOVERABLE_ERROR,
	COMMUNICATIONS_ERROR, PRINTER_CLOSED, PAPER_MANUAL_FEED, MECHANICAL_ERROR, AUTORECOVERABLE_ERROR
}
